{% set version = "7.2.0" %}

package:
  name: devpi-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/devpi-client/devpi-client-{{ version }}.tar.gz
  sha256: c143368458c3878ba7bee6a1d9b418e2e659571a3856614f58d76b8a28269d7b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - devpi = devpi.main:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - check-manifest >=0.28
    - colorama
    - devpi-common >=4,<5
    - iniconfig
    - pkginfo >=1.4.2
    - platformdirs
    - pluggy >=0.6.0,<2.0
    - python >=3.7
    - python-build >=0.7.0
    - tomli

test:
  imports:
    - devpi
  commands:
    - pip check
    - devpi --help
  requires:
    - pip

about:
  home: https://devpi.net
  summary: devpi upload/install/... workflow commands for Python developers
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/devpi/devpi
  doc_url: https://doc.devpi.net

extra:
  recipe-maintainers:
    - bollwyvl
